[font]
size = 13.25

[font.normal]
family = "UbuntuMonoNerdFont"
style = "Regular"

[font.italic]
family = "UbuntuMonoNerdFont"
style = "Italic"

[font.bold]
family = "UbuntuMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "UbuntuMonoNerdFont"
style = "BoldItalic"

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"
